const {
  User,
  Bike,
  Ticket,
  Labor,
  Product,
  Order,
  Todo,
  Cart,
  TicketLabor,
  TicketProduct,
  OrderProduct,
} = require("./models");

const users = [
  {firstname: "Tobin", lastname: "Waters", email: "tobinsemail@email.com", phone: "1111111111", address: "123 some street, some town, UT 12345", employee: "true"},
  {firstname: "Billy", lastname: "Bobby", email: "billyemail@email.com", phone: "2222222222", address: "123 some street, some town, UT 12345", employee: "false"},
  {firstname: "Bobby", lastname: "Billy", email: "bobbyemail@email.com", phone: "3333333333", address: "123 some street, some town, UT 12345", employee: "false"},
  {firstname: "Bill", lastname: "BillyBob", email: "billemail@email.com", phone: "4444444444", address: "123 some street, some town, UT 12345", employee: "false"},
  {firstname: "Bob", lastname: "BobbyBill", email: "bobemail@email.com", phone: "5555555555", address: "123 some street, some town, UT 12345", employee: "false"},
  {firstname: "Timmy", lastname: "Tommy", email: "timmyemail@email.com", phone: "6666666666", address: "123 some street, some town, UT 12345", employee: "false"},
  {firstname: "Tommy", lastname: "Timmy", email: "tommyemail@email.com", phone: "7777777777", address: "123 some street, some town, UT 12345", employee: "false"},
  {firstname: "Tim", lastname: "TommyTim", email: "timemail@email.com", phone: "8888888888", address: "123 some street, some town, UT 12345", employee: "false"},
  {firstname: "Tom", lastname: "TimmyTom", email: "tomemail@email.com", phone: "9999999999", address: "123 some street, some town, UT 12345", employee: "false"},
  {firstname: "Leeroy", lastname: "Jenkins", email: "leeroyemail@email.com", phone: "0000000000", address: "123 some street, some town, UT 12345", employee: "true"},
]
const bikes = [
  {userId: "1", brand: "Santa Cruz", model: "Bronson", color: "Black/Pink", size: "small", type: "Full Suspension"},
  {userId: "2", brand: "Cannondale", model: "F29", color: "Green", size: "small", type: "Hardtail"},
  {userId: "3", brand: "Ritchey", model: "Outback", color: "Red", size: "small", type: "Gravel"},
  {userId: "4", brand: "Pinarello", model: "F12", color: "Silver", size: "medium", type: "Road"},
  {userId: "5", brand: "Salsa", model: "Vaya", color: "Yellow", size: "medium", type: "Commuter"},
  {userId: "6", brand: "Orbea", model: "Gain", color: "Blue", size: "medium", type: "E-Bike"},
  {userId: "7", brand: "Giant", model: "Trance", color: "Grey", size: "large", type: "Full Suspension"},
  {userId: "8", brand: "Scott", model: "Scale", color: "Black", size: "large", type: "Hardtail"},
  {userId: "9", brand: "Open", model: "UPPER", color: "Purple", size: "large", type: "Gravel"},
  {userId: "10", brand: "Time", model: "Scylon", color: "Pink", size: "XL", type: "Road"},
  {userId: "9", brand: "Santa Cruz", model: "Nomad", color: "Red", size: "Medium", type: "Full Suspension"},
  {userId: "8", brand: "Cannondale", model: "Scalpel", color: "Blue", size: "small", type: "Full Suspension"},
  {userId: "7", brand: "Ritchey", model: "Break Away", color: "Green", size: "Large", type: "Gravel"},
  {userId: "6", brand: "Pinarello", model: "Grevil", color: "Black", size: "medium", type: "Gravel"},
  {userId: "4", brand: "Salsa", model: "Poseidon", color: "Teal", size: "XL", type: "Commuter"},
  {userId: "5", brand: "Orbea", model: "Oiz", color: "Silver", size: "medium", type: "Full Suspension"},
  {userId: "3", brand: "Giant", model: "Glory", color: "Blue", size: "Small", type: "Full Suspension"},
  {userId: "2", brand: "Scott", model: "Spark", color: "Purple", size: "large", type: "Hull Suspension"},
  {userId: "10", brand: "Open", model: "MIND", color: "Blue", size: "Medium", type: "Road"},
  {userId: "1", brand: "Time", model: "Alp D'Huez", color: "Red", size: "XS", type: "Road"},
]
const tickets = [
  {userId: "1", bikeId: "1", externalNotes: "", internalNotes: "", dueDate: '2024-01-12', location: 'Storage', status: 'Checked In', total: '0.00'},
  {userId: "2", bikeId: "2", externalNotes: "", internalNotes: "", dueDate: '2024-02-12', location: 'Storage', status: 'Finished', total: '0.00'},
  {userId: "3", bikeId: "3", externalNotes: "", internalNotes: "", dueDate: '2024-03-12', location: 'Storage', status: 'Done and Paid', total: '0.00'},
  {userId: "4", bikeId: "4", externalNotes: "", internalNotes: "", dueDate: '2024-04-12', location: 'Storage', status: 'Waiting for Parts', total: '0.00'},
  {userId: "5", bikeId: "5", externalNotes: "", internalNotes: "", dueDate: '2024-05-12', location: 'Storage', status: 'Not Here', total: '0.00'},
  {userId: "6", bikeId: "6", externalNotes: "", internalNotes: "", dueDate: '2024-06-12', location: 'Storage', status: 'Checked In', total: '0.00'},
  {userId: "7", bikeId: "7", externalNotes: "", internalNotes: "", dueDate: '2024-07-12', location: 'Storage', status: 'Finished', total: '0.00'},
  {userId: "8", bikeId: "8", externalNotes: "", internalNotes: "", dueDate: '2024-08-12', location: 'Storage', status: 'Checked In', total: '0.00'},
  {userId: "9", bikeId: "9", externalNotes: "", internalNotes: "", dueDate: '2023-09-12', location: 'Storage', status: 'Finished', total: '0.00'},
  {userId: "10", bikeId: "10", externalNotes: "", internalNotes: "", dueDate: '2023-1-12', location: 'Storage', status: 'Done and Paid', total: '0.00'},
  {userId: "1", bikeId: "20", externalNotes: "", internalNotes: "", dueDate: '2024-01-12', location: 'Storage', status: 'Checked In', total: '0.00'},
  {userId: "2", bikeId: "18", externalNotes: "", internalNotes: "", dueDate: '2024-02-12', location: 'Storage', status: 'Finished', total: '0.00'},
  {userId: "3", bikeId: "17", externalNotes: "", internalNotes: "", dueDate: '2024-03-12', location: 'Storage', status: 'Done and Paid', total: '0.00'},
  {userId: "4", bikeId: "15", externalNotes: "", internalNotes: "", dueDate: '2024-04-12', location: 'Storage', status: 'Waiting for Parts', total: '0.00'},
  {userId: "5", bikeId: "16", externalNotes: "", internalNotes: "", dueDate: '2024-05-12', location: 'Storage', status: 'Not Here', total: '0.00'},
  {userId: "6", bikeId: "14", externalNotes: "", internalNotes: "", dueDate: '2024-06-12', location: 'Storage', status: 'Checked In', total: '0.00'},
  {userId: "7", bikeId: "13", externalNotes: "", internalNotes: "", dueDate: '2024-07-12', location: 'Storage', status: 'Finished', total: '0.00'},
  {userId: "8", bikeId: "12", externalNotes: "", internalNotes: "", dueDate: '2024-08-12', location: 'Storage', status: 'Checked In', total: '0.00'},
  {userId: "9", bikeId: "11", externalNotes: "", internalNotes: "", dueDate: '2023-09-12', location: 'Storage', status: 'Finished', total: '0.00'},
  {userId: "10", bikeId: "19", externalNotes: "", internalNotes: "", dueDate: '2023-1-12', location: 'Storage', status: 'Done and Paid', total: '0.00'},
]
const labor = [
  //General
  {laborTitle: 'labor - basic tune (does not include parts)', laborPrice: '80', laborTime: '45'},
  {laborTitle: 'labor - major tune (does not include parts)', laborPrice: '150', laborTime: '90'},
  {laborTitle: 'labor - full overhaul (does not include parts)', laborPrice: '250', laborTime: '150'},
  {laborTitle: 'labor - light bike wash', laborPrice: '25', laborTime: '15'},
  {laborTitle: 'labor - thorough bike wash', laborPrice: '45', laborTime: '25'},
  {laborTitle: 'labor - drivetrain clean (on bike)', laborPrice: '35', laborTime: '20'},
  {laborTitle: 'labor - bike assembly', laborPrice: '75', laborTime: '45'},
  {laborTitle: 'labor - bike boxing', laborPrice: '75', laborTime: '45'},
  
  //Brakes
  {laborTitle: 'labor - mechanical brake adjustment', laborPrice: '10', laborTime: '10'},
  {laborTitle: 'labor - disk brake adjustment', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - external brake cable install', laborPrice: '15', laborTime: '15'},
  {laborTitle: 'labor - internal brake cable install', laborPrice: '25', laborTime: '20'},
  {laborTitle: 'labor - install new shoe brake pads', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - install new disc brake pads', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - install disc brake rotor', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - hydraulic brake bleed', laborPrice: '35', laborTime: '20'},
  {laborTitle: 'labor - hydraulic lever bleed', laborPrice: '25', laborTime: '15'},
  {laborTitle: 'labor - hydraulic remote bleed', laborPrice: '30', laborTime: '15'},
  {laborTitle: 'labor - face brake mounts', laborPrice: '45', laborTime: '30'},
  {laborTitle: 'labor - external mountain cable brake system install', laborPrice: '40', laborTime: '30'},
  {laborTitle: 'labor - external hydraulic brake system install', laborPrice: '50', laborTime: '40'},
  {laborTitle: 'labor - mountain cable brake lever install', laborPrice: '30', laborTime: '20'},
  {laborTitle: 'labor - hydraulic mountain lever install', laborPrice: '40', laborTime: '25'},
  {laborTitle: 'labor - internal mountain cable brake system install', laborPrice: '50', laborTime: '40'},
  {laborTitle: 'labor - internal hydraulic brake system install', laborPrice: '60', laborTime: '50'},
  {laborTitle: 'labor - external brake cable and housing replacement', laborPrice: '30', laborTime: '25'},
  {laborTitle: 'labor - internal brake cable and housing replacement', laborPrice: '40', laborTime: '35'},
  {laborTitle: 'labor - external hydraulic line replacement', laborPrice: '40', laborTime: '30'},
  {laborTitle: 'labor - internal hydraulic line replacement', laborPrice: '50', laborTime: '40'},
  {laborTitle: 'labor - mechanical brake caliper replacement', laborPrice: '30', laborTime: '20'},
  {laborTitle: 'labor - hydraulic disc brake caliper replacement', laborPrice: '40', laborTime: '25'},
  
  //Drivetrain
  {laborTitle: 'labor - derailleur adjustment', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - install new derailleur cable', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - external derailleur cable and housing replacement', laborPrice: '30', laborTime: '25'},
  {laborTitle: 'labor - internal derailleur cable and housing replacement', laborPrice: '40', laborTime: '30'},
  {laborTitle: 'labor - mechanical derailleur install', laborPrice: '25', laborTime: '20'},
  {laborTitle: 'labor - mechanical flatbar shifter install', laborPrice: '25', laborTime: '20'},
  {laborTitle: 'labor - electronic derailleur install', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - electronic flatbar shifter install', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - mechanical dropbar sti shifter install', laborPrice: '60', laborTime: '50'},
  {laborTitle: 'labor - mechanical dropbar sti shifter set install', laborPrice: '100', laborTime: '100'},
  {laborTitle: 'labor - mechanical / hydraulic dropbar sti shifter install', laborPrice: '70', laborTime: '60'},
  {laborTitle: 'labor - mechanical / hydraulic dropbar sti shifter set install', laborPrice: '130', laborTime: '120'},
  {laborTitle: 'labor - electronic mechanical dropbar sti shifter install', laborPrice: '45', laborTime: '40'},
  {laborTitle: 'labor - electronic mechanical dropbar sti shifter set install', laborPrice: '90', laborTime: '80'},
  {laborTitle: 'labor - electronic hydraulic dropbar sti shifter install', laborPrice: '65', laborTime: '55'},
  {laborTitle: 'labor - electronic hydraulic dropbar sti shifter set install', laborPrice: '120', laborTime: '110'},
  {laborTitle: 'labor - derailleur hanger alignment', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - derailleur hanger install', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - threaded bb install', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - threaded bb overhaul', laborPrice: '25', laborTime: '20'},
  {laborTitle: 'labor - pressfit bb install', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - pressfit bb overhaul', laborPrice: '30', laborTime: '25'},
  {laborTitle: 'labor - thread together bb install', laborPrice: '25', laborTime: '20'},
  {laborTitle: 'labor - thread together bb overhaul', laborPrice: '35', laborTime: '30'},
  {laborTitle: 'labor - loost ball bearing bb install', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - loost ball bearing bb overhaul', laborPrice: '35', laborTime: '25'},
  {laborTitle: 'labor - bb cartridge bearing replacement', laborPrice: '30', laborTime: '20'},
  {laborTitle: 'labor - crank install', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - chainring install', laborPrice: '35', laborTime: '25'},
  {laborTitle: 'labor - chain install', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - cassette install', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - face bb shell and chase threads', laborPrice: '45', laborTime: '35'},
  {laborTitle: 'labor - freewheel install', laborPrice: '15', laborTime: '10'},
  
  //Fork and Headset
  {laborTitle: 'labor - headset adjustment', laborPrice: '10', laborTime: '10'},
  {laborTitle: 'labor - cartridge bearing headset overhaul', laborPrice: '25', laborTime: '20'},
  {laborTitle: 'labor - loose ball bearing headset overhaul', laborPrice: '35', laborTime: '25'},
  {laborTitle: 'labor - headset with cups install', laborPrice: '45', laborTime: '35'},
  {laborTitle: 'labor - integrated headset install', laborPrice: '30', laborTime: '25'},
  {laborTitle: 'labor - fork install', laborPrice: '55', laborTime: '40'},
  {laborTitle: 'labor - basic suspension fork service', laborPrice: '75', laborTime: '60'},
  {laborTitle: 'labor - cut steerer tube', laborPrice: '35', laborTime: '25'},
  {laborTitle: 'labor - install new crown race', laborPrice: '25', laborTime: '20'},
  
  //Wheels and Hubs
  {laborTitle: 'labor - standard wheel true', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - major wheel true (dishing, hops, major wobble)', laborPrice: '30', laborTime: '25'},
  {laborTitle: 'labor - spoke replacement', laborPrice: '35', laborTime: '25'},
  {laborTitle: 'labor - replace all nipples', laborPrice: '75', laborTime: '60'},
  {laborTitle: 'labor - replace all spokes', laborPrice: '85', laborTime: '70'},
  {laborTitle: 'labor - wheel build', laborPrice: '75', laborTime: '60'},
  {laborTitle: 'labor - replace rim', laborPrice: '85', laborTime: '70'},
  {laborTitle: 'labor - hub adjustment', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - rear hub loose ball bearing overhaul', laborPrice: '35', laborTime: '25'},
  {laborTitle: 'labor - front hub loost ball bearing overhaul', laborPrice: '25', laborTime: '15'},
  {laborTitle: 'labor - front hub cartridge bearing install', laborPrice: '25', laborTime: '15'},
  {laborTitle: 'labor - rear hub cartridge bearing install', laborPrice: '30', laborTime: '20'},
  {laborTitle: 'labor - freehub body install', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - freehub body overhaul', laborPrice: '30', laborTime: '25'},
  {laborTitle: 'labor - front hub overhaul', laborPrice: '35', laborTime: '25'},
  {laborTitle: 'labor - rear hub overhaul', laborPrice: '45', laborTime: '35'},
  {laborTitle: 'labor - chris king front hub overhaul', laborPrice: '45', laborTime: '35'},
  {laborTitle: 'labor - chris king rear hub overhaul', laborPrice: '70', laborTime: '50'},
  {laborTitle: 'labor - chris king front hub bearing service', laborPrice: '30', laborTime: '20'},
  {laborTitle: 'labor - chris king rear hub bearing service', laborPrice: '50', laborTime: '40'},
  {laborTitle: 'labor - chris king freehub bearing service', laborPrice: '30', laborTime: '20'},
  {laborTitle: 'labor - wheel set install', laborPrice: '55', laborTime: '40'},
  
  //Tire / Tube setup
  {laborTitle: 'labor - tube / tire install', laborPrice: '12', laborTime: '5'},
  {laborTitle: 'labor - tubeless tire install', laborPrice: '25', laborTime: '15'},
  {laborTitle: 'labor - tubeless tape rim', laborPrice: '10', laborTime: '5'},
  {laborTitle: 'labor - cushcore tubeless tire install', laborPrice: '45', laborTime: '25'},
  {laborTitle: 'labor - flat protection strip install', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - tubular tire install', laborPrice: '60', laborTime: '45'},
  
  //Handlebar Stem and Seatpost
  {laborTitle: 'labor - install stem', laborPrice: '10', laborTime: '5'},
  {laborTitle: 'labor - install flatbar', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - install dropbar', laborPrice: '30', laborTime: '25'},
  {laborTitle: 'labor - install bar tape', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - install grips', laborPrice: '10', laborTime: '5'},
  {laborTitle: 'labor - install saddle', laborPrice: '10', laborTime: '5'},
  {laborTitle: 'labor - install seatpost', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - install internal dropper post', laborPrice: '60', laborTime: '50'},
  {laborTitle: 'labor - install external dropper post', laborPrice: '45', laborTime: '35'},
  {laborTitle: 'labor - install dropper cable', laborPrice: '25', laborTime: '20'},
  {laborTitle: 'labor - install dropper cable and housing', laborPrice: '35', laborTime: '25'},
  
  //Rear shock and suspension
  {laborTitle: 'labor - basic rear shock service', laborPrice: '60', laborTime: '45'},
  {laborTitle: 'labor - install rear shock', laborPrice: '20', laborTime: '15'},
  {laborTitle: 'labor - install rear shock lockout cable', laborPrice: '15', laborTime: '10'},
  {laborTitle: 'labor - install rear shock lockout cable and housing', laborPrice: '30', laborTime: '20'},
  {laborTitle: 'labor - replace shock bushings', laborPrice: '30', laborTime: '25'},
  {laborTitle: 'labor - rebuild suspension linkage', laborPrice: '90', laborTime: '75'},
  {laborTitle: 'labor - service suspension linkage', laborPrice: '150', laborTime: '120'},
]
const products = [
  {productTitle: 'shimano rear derailleur', productPrice: '75.99'},
  {productTitle: 'shimano front derailleur', productPrice: '45.99'},
  {productTitle: 'shimano rear flatbar shifter', productPrice: '30.99'},
  {productTitle: 'shimano front flatbar shifter', productPrice: '30.99'},
  {productTitle: 'shimano road sti shifter', productPrice: '55.99'},
  {productTitle: 'shimano cassette', productPrice: '45.99'},
  {productTitle: 'shimano chain', productPrice: '32.99'},
  {productTitle: 'pro saddle', productPrice: '53.99'},
  {productTitle: 'fizik saddle', productPrice: '76.99'},
  {productTitle: 'mountain handlebar', productPrice: '35.99'},
  {productTitle: 'road dropbar handlebar', productPrice: '40.99'},
  {productTitle: 'dt swiss wheelset', productPrice: '475.99'},
  {productTitle: 'raceface wheelset', productPrice: '675.99'},
  {productTitle: 'fulcrum wheelset', productPrice: '350.99'},
  {productTitle: 'sram rear derailleur', productPrice: '70.99'},
  {productTitle: 'sram front derailleur', productPrice: '40.99'},
  {productTitle: 'sram rear flatbar shifter', productPrice: '25.99'},
  {productTitle: 'sram front flatbar shifter', productPrice: '27.99'},
  {productTitle: 'sram road sti shifter', productPrice: '46.99'},
  {productTitle: 'sram cassette', productPrice: '25.99'},
  {productTitle: 'sram chain', productPrice: '20.99'},
  {productTitle: 'easton seatpost', productPrice: '55.99'},
  {productTitle: 'raceface grips', productPrice: '15.99'},
  {productTitle: 'shimano crank', productPrice: '120.99'},
  {productTitle: 'sram crank', productPrice: '110.99'},
  {productTitle: 'shimano bottom bracket', productPrice: '25.99'},
  {productTitle: 'sram bottom bracket', productPrice: '30.99'},
  {productTitle: 'derailleur cable', productPrice: '5.99'},
  {productTitle: 'brake cable', productPrice: '5.99'},
  {productTitle: 'derailleur housing', productPrice: '3.99'},
  {productTitle: 'brake housing', productPrice: '2.99'},
  {productTitle: 'hydraulic brake hose', productPrice: '45.99'},
  {productTitle: 'shimano hydraulic brake', productPrice: '85.99'},
  {productTitle: 'sram hydraulic brake', productPrice: '82.99'},

]
const orders= [
  {userId: "1", orderTotal: '25.99'},
  {userId: "2", orderTotal: '39.99'},
  {userId: "3", orderTotal: '15.99'},
  {userId: "4", orderTotal: '100.99'},
  {userId: "5", orderTotal: '75.99'},
]
const todo = [
  {complete: "false", description: 'Organize tires'},
  {complete: "false", description: 'Clean under benches'},
  {complete: "false", description: 'Wipe down surfaces'},
  {complete: "false", description: 'Label new inventory'},
]
const carts = [
  {userId: '1', productId: '1', quantity: "1"},
  {userId: '2', productId: '2', quantity: "1"},
  {userId: '3', productId: '3', quantity: "1"},
  {userId: '4', productId: '4', quantity: "1"},
  {userId: '5', productId: '5', quantity: "1"},
]
const ticketLabor = [
  {ticketId: "1", laborId: "1", quantity: "1"},
  {ticketId: "2", laborId: "2", quantity: "1"},
  {ticketId: "3", laborId: "3", quantity: "1"},
  {ticketId: "4", laborId: "4", quantity: "1"},
  {ticketId: "5", laborId: "5", quantity: "1"},
  {ticketId: "6", laborId: "6", quantity: "1"},
  {ticketId: "7", laborId: "7", quantity: "1"},
  {ticketId: "8", laborId: "8", quantity: "1"},
  {ticketId: "9", laborId: "1", quantity: "1"},
  {ticketId: "1", laborId: "2", quantity: "1"},
  {ticketId: "2", laborId: "3", quantity: "1"},
  {ticketId: "3", laborId: "4", quantity: "1"},
  {ticketId: "4", laborId: "5", quantity: "1"},
  {ticketId: "5", laborId: "6", quantity: "1"},
  {ticketId: "6", laborId: "7", quantity: "1"},
  {ticketId: "7", laborId: "8", quantity: "1"},
  {ticketId: "8", laborId: "9", quantity: "1"},
  {ticketId: "9", laborId: "3", quantity: "1"},
]
const ticketProduct = [
  {ticketId: "1", productId: "1", quantity: "1"},
  {ticketId: "2", productId: "2", quantity: "1"},
  {ticketId: "3", productId: "3", quantity: "1"},
  {ticketId: "4", productId: "4", quantity: "1"},
  {ticketId: "5", productId: "5", quantity: "1"},
  {ticketId: "6", productId: "1", quantity: "1"},
  {ticketId: "7", productId: "2", quantity: "1"},
  {ticketId: "8", productId: "3", quantity: "1"},
  {ticketId: "9", productId: "4", quantity: "1"},
  {ticketId: "1", productId: "5", quantity: "1"},
  {ticketId: "2", productId: "1", quantity: "1"},
  {ticketId: "3", productId: "2", quantity: "1"},
  {ticketId: "4", productId: "3", quantity: "1"},
  {ticketId: "5", productId: "4", quantity: "1"},
  {ticketId: "6", productId: "5", quantity: "1"},
  {ticketId: "7", productId: "1", quantity: "1"},
  {ticketId: "8", productId: "2", quantity: "1"},
  {ticketId: "9", productId: "3", quantity: "1"},
]
const orderProduct = [
  {orderId: "1", productId: "1", quantity: "1"},
  {orderId: "2", productId: "2", quantity: "1"},
  {orderId: "3", productId: "3", quantity: "1"},
  {orderId: "4", productId: "4", quantity: "1"},
  {orderId: "5", productId: "5", quantity: "1"},
]

const seed = async () => {
  try {
    await User.bulkCreate(users);
    await Bike.bulkCreate(bikes);
    await Ticket.bulkCreate(tickets);
    await Labor.bulkCreate(labor);
    await Product.bulkCreate(products);
    await Order.bulkCreate(orders);
    await Todo.bulkCreate(todo);
    await Cart.bulkCreate(carts);
    await TicketLabor.bulkCreate(ticketLabor);
    await TicketProduct.bulkCreate(ticketProduct);
    await OrderProduct.bulkCreate(orderProduct);
  }
  catch(err) {
    console.log(err)
  }
};

module.exports = seed;

